# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
target 'ParkDND' do
  pod 'GoogleMaps'
  pod 'GooglePlaces'


  # Pods for ParkDND

  target 'ParkDNDTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ParkDNDUITests' do
    # Pods for testing
  end

end
